CONTIKI_PROJECT = udp-server udp-client
all: $(CONTIKI_PROJECT)

CONTIKI = ../..

include $(CONTIKI)/Makefile.dir-variables
MODULES += $(CONTIKI_NG_SERVICES_DIR)/simple-udp

include $(CONTIKI)/Makefile.include
